# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

# IMPORTANT: Specify your personal configuration here. After having done so, run the following command to avoid git committing the file with your personal configurations:
# git update-index --skip-worktree FILENAME
# and if you want to track the changes again use this command:
# git update-index --no-skip-worktree FILENAME
# See also: https://stackoverflow.com/questions/13630849/git-difference-between-assume-unchanged-and-skip-worktree#
private:
  keys:
    entsoe_api:

remote:
  ssh: ""
  path: ""
