no_import_me:
  solving:
    constraints:
      limit_eu_de: 0
  sector:
    electrolysis_costs: false
    import:
      non_eu: false

no_import_le:
  solving:
    constraints:
      limit_eu_de: 0
  sector:
    electrolysis_costs: "low"
    import:
      non_eu: false

no_import_he:
  solving:
    constraints:
      limit_eu_de: 0
  sector:
    electrolysis_costs: "high"
    import:
      non_eu: false

no_import_he:
  sector:
    electrolysis_costs: "high"
    import:
      non_eu: false
      limit_eu_de: 
        2030: 0
        2035: 0
        2040: 0
        2045: 0

####################
eu_import_me_all:
  sector:
    electrolysis_costs: false
    import:
      non_eu: false
      carriers: "all"

eu_import_le_all:
  sector:
    electrolysis_costs: "low"
    import:
      non_eu: false
      carriers: "all"

eu_import_he_all:
  sector:
    electrolysis_costs: "high"
    import:
      non_eu: false
      carriers: "all"

eu_import_le_eleh2:
  sector:
    electrolysis_costs: "low"
    import:
      non_eu: false
      carriers: "eleh2"

eu_import_he_eleh2:
  sector:
    electrolysis_costs: "high"
    import:
      non_eu: false
      carriers: "eleh2"

####################
all_import_me_all:
  sector:
    electrolysis_costs: false
    import:
      non_eu: true
      carriers: "all"

all_import_le_all:
  sector:
    electrolysis_costs: "low"
    import:
      non_eu: true
      carriers: "all"

all_import_he_all:
  sector:
    electrolysis_costs: "high"
    import:
      non_eu: true
      carriers: "all"

all_import_le_eleh2:
  sector:
    electrolysis_costs: "low"
    import:
      non_eu: true
      carriers: "eleh2"

all_import_he_eleh2:
  sector:
    electrolysis_costs: "high"
    import:
      non_eu: true
      carriers: "eleh2"

####################
all_import_le+10:
  sector:
    electrolysis_costs: "low"
    import:
      non_eu: true
      carriers: "all"
      cost_factor: 1.1

all_import_he+10:
  sector:
    electrolysis_costs: "high"
    import:
      non_eu: true
      carriers: "all"
      cost_factor: 1.1

all_import_le-10:
  sector:
    electrolysis_costs: "low"
    import:
      non_eu: true
      carriers: "all"
      cost_factor: 0.9

all_import_he-10:
  sector:
    electrolysis_costs: "high"
    import:
      non_eu: true
      carriers: "all"
      cost_factor: 0.9

all_import_le-20:
  sector:
    electrolysis_costs: "low"
    import:
      non_eu: true
      carriers: "all"
      cost_factor: 0.8

all_import_he-20:
  sector:
    electrolysis_costs: "high"
    import:
      non_eu: true
      carriers: "all"
      cost_factor: 0.8