# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT
no_import_me:
# no net import of energy carriers to Germany

  iiasa_database:
    reference_scenario: KN2045_Bal_v4
    fallback_reference_scenario: KN2045_Bal_v4
  co2_budget_DE_source: KSG

  solving:
    constraints:
      limit_non_eu_de: true # true equals 0, number or false
      limit_eu_de: true # true equals 0 or false
      limits_capacity_min:
        Link:
          H2 Electrolysis:
            DE:
              2030: 5

      co2_budget_national:
        2020:
          DE: 0.699
        2025:
          DE: 0.551
        2030:
          DE: 0.362
        2035:
          DE: 0.221
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.048
  import:
    enable: false

  industry:
    steam_biomass_fraction: 0.4
    steam_hydrogen_fraction: 0.3
    steam_electricity_fraction: 0.3

    St_primary_fraction:
      2020: 0.7023
      2025: 0.705
      2030: 0.6929
      2035: 0.6598
      2040: 0.6273
      2045: 0.6047
    DRI_fraction:
      2020: 0.0
      2025: 0.0
      2030: 0.2011
      2035: 0.496
      2040: 0.7729
      2045: 1.0
  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9361
      2030: 0.8558
      2035: 0.7713
      2040: 0.6948
      2045: 0.6909
eu_import_me_all:
# unlimited net import of energy carriers to Germany

  iiasa_database:
    reference_scenario: KN2045_Bal_v4
    fallback_reference_scenario: KN2045_Bal_v4
  co2_budget_DE_source: KSG

  solving:
    constraints:
      limit_non_eu_de: true # true equals 0, number or false
      limit_eu_de: false # true equals 0 or false
      limits_capacity_min:
        Link:
          H2 Electrolysis:
            DE:
              2030: 5

      co2_budget_national:
        2020:
          DE: 0.699
        2025:
          DE: 0.551
        2030:
          DE: 0.362
        2035:
          DE: 0.221
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.048
  import:
    enable: false

  industry:
    steam_biomass_fraction: 0.4
    steam_hydrogen_fraction: 0.3
    steam_electricity_fraction: 0.3

    St_primary_fraction:
      2020: 0.7023
      2025: 0.705
      2030: 0.6929
      2035: 0.6598
      2040: 0.6273
      2045: 0.6047
    DRI_fraction:
      2020: 0.0
      2025: 0.0
      2030: 0.2011
      2035: 0.496
      2040: 0.7729
      2045: 1.0
  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9361
      2030: 0.8558
      2035: 0.7713
      2040: 0.6948
      2045: 0.6909
all_import_me_all:
# unlimited net import of energy carriers to Germany even from non-European countries

  iiasa_database:
    reference_scenario: KN2045_Bal_v4
    fallback_reference_scenario: KN2045_Bal_v4
  co2_budget_DE_source: KSG

  solving:
    constraints:
      limit_non_eu_de: false # true equals 0, number or false
      limit_eu_de: false # true equals 0, number or false
      limits_capacity_min:
        Link:
          H2 Electrolysis:
            DE:
              2030: 5

      co2_budget_national:
        2020:
          DE: 0.699
        2025:
          DE: 0.551
        2030:
          DE: 0.362
        2035:
          DE: 0.221
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.048
  import:
    enable: true

  industry:
    steam_biomass_fraction: 0.4
    steam_hydrogen_fraction: 0.3
    steam_electricity_fraction: 0.3

    St_primary_fraction:
      2020: 0.7023
      2025: 0.705
      2030: 0.6929
      2035: 0.6598
      2040: 0.6273
      2045: 0.6047
    DRI_fraction:
      2020: 0.0
      2025: 0.0
      2030: 0.2011
      2035: 0.496
      2040: 0.7729
      2045: 1.0
  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9361
      2030: 0.8558
      2035: 0.7713
      2040: 0.6948
      2045: 0.6909
all_import_me_all_100:
# unlimited net import of energy carriers to Germany even from non-European countries

  iiasa_database:
    reference_scenario: KN2045_Bal_v4
    fallback_reference_scenario: KN2045_Bal_v4
  co2_budget_DE_source: KSG

  solving:
    constraints:
      limit_non_eu_de: 100 # true equals 0, number or false
      limit_eu_de: false # true equals 0 or false
      limits_capacity_min:
        Link:
          H2 Electrolysis:
            DE:
              2030: 5

      co2_budget_national:
        2020:
          DE: 0.699
        2025:
          DE: 0.551
        2030:
          DE: 0.362
        2035:
          DE: 0.221
        2040:
          DE: 0.09
        2045:
          DE: -0.05
        2050:
          DE: -0.048
  import:
    enable: true

  industry:
    steam_biomass_fraction: 0.4
    steam_hydrogen_fraction: 0.3
    steam_electricity_fraction: 0.3
    St_primary_fraction:
      2020: 0.7023
      2025: 0.705
      2030: 0.6929
      2035: 0.6598
      2040: 0.6273
      2045: 0.6047
    DRI_fraction:
      2020: 0.0
      2025: 0.0
      2030: 0.2011
      2035: 0.496
      2040: 0.7729
      2045: 1.0
  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 0.9361
      2030: 0.8558
      2035: 0.7713
      2040: 0.6948
      2045: 0.6909
