# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT


8Gt_Bal_v3:
  iiasa_database:
    reference_scenario: 8Gt_Bal_v3
    fallback_reference_scenario: 8Gt_Bal_v3
  co2_budget_DE_source: KSG

  costs:
    horizon: "mean"
    NEP: 2023
    transmission: "overhead" # either overhead line ("overhead") or underground cable ("underground")

  # boundary condition of maximum volumes
  limits_volume_max:
    # constrain electricity import in TWh
    electricity_import:
      DE:
        2020: -20
        2025: 0
        2030: 0
        2035: 40
        2040: 80
        2045: 125
    electrolysis:
      DE:
        2020: 0
        2025: 5
        2030: 45
        2035: 130
        2040: 215
        2045: 300
    h2_derivate_import:
      DE:
        2020: 0
        2025: 0
        2030: 10
        2035: 105
        2040: 200
        2045: 300
    h2_import:
      DE:
        2020: 0
        2025: 5
        2030: 15
        2035: 115
        2040: 220
        2045: 325
  limits_volume_min:
    electrolysis:
      DE:
        2020: 0
        2025: 0
        2030: 0
        2035: 0
        2040: 0
        2045: 0

8Gt_Elec_v3:
  iiasa_database:
    reference_scenario: 8Gt_Elec_v3
    fallback_reference_scenario: 8Gt_Elec_v3
  co2_budget_DE_source: KSG

  costs:
    horizon: "mean"
    NEP: 2023
    transmission: "overhead" # either overhead line ("overhead") or underground cable ("underground")

  limits_volume_max:
    # constrain electricity import in TWh
    electricity_import:
      DE:
        2020: -20
        2025: 0
        2030: 0
        2035: 50
        2040: 100
        2045: 150
    electrolysis:
      DE:
        2020: 0
        2025: 5
        2030: 45
        2035: 95
        2040: 145
        2045: 200
    h2_derivate_import:
      DE:
        2020: 0
        2025: 0
        2030: 10
        2035: 70
        2040: 130
        2045: 200
    h2_import:
      DE:
        2020: 0
        2025: 5
        2030: 10
        2035: 90
        2040: 170
        2045: 250
  limits_volume_min:
    electrolysis:
      DE:
        2020: 0
        2025: 0
        2030: 0
        2035: 0
        2040: 0
        2045: 0

8Gt_H2_v3:
  iiasa_database:
    reference_scenario: 8Gt_H2_v3
    fallback_reference_scenario: 8Gt_H2_v3
  co2_budget_DE_source: KSG

  costs:
    horizon: "mean"
    NEP: 2023
    transmission: "overhead" # either overhead line ("overhead") or underground cable ("underground")

  limits_volume_max:
    # constrain electricity import in TWh
    electricity_import:
      DE:
        2020: -20
        2025: 0
        2030: 0
        2035: 30
        2040: 70
        2045: 100 # scenario guidelines

    # constrain hydrogen import in TWh
    h2_import:
      DE:
        2020: 0
        2025: 5
        2030: 45 # scenario guidelines 
        2035: 155
        2040: 265
        2045: 400 # scenario guidelines
    # import of h2 derivatives in TWh
    h2_derivate_import:
      DE:
        2020: 0
        2025: 0
        2030: 10 # scenario guidelines
        2035: 140
        2040: 270
        2045: 400 # scenario guidelines
    electrolysis:
      DE:
        2020: 0
        2025: 5
        2030: 45 # scenario guidelines
        2035: 160
        2040: 275
        2045: 400 # scenario guidelines

  limits_volume_min:
    electrolysis:
      DE:
        2025: 0
        2030: 0
        2035: 0
        2040: 0
        2045: 200
